[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "utils"
version = "1.0.0"
description = "Internal utilities package"
requires-python = ">=3.9"

# CORE dependencies: always installed
dependencies = [
"pydantic>=2.0"
]

[project.optional-dependencies]
time = ["python-dateutil"]
geospatial = ["shapely"]
all = ["utils[time, geospatial]"]

[tool.setuptools.packages.find]
where = ["."]